Task5
isikbelkis/Background-App pull request #1
Opened 2024-09-10 14:52 UTC by isikbelkis

2024-09-10 21:00 UTC, TamerSarioglu requested changes
AppDatabase yok uygulamada? 
Lokal databese eklenmeye çalışılmış sanırım ancak ben mi göremedim?

2024-09-12 08:00 UTC, kerimisoffline requested changes
Eline sağlık

2024-09-12 08:00 UTC, kerimisoffline commented on app/src/main/java/com/example/backgroundapp/model/Photo.kt
> +data class PhotoItem(
iç içe data class tanımlamaları yapmayalım. hepsini ayıralım. ayrı classlarda olsun. gerekirse isimlendirmeleride düzenleyelim. Mesela iki farklı Links olduğu için birine başka bir isim verebiliriz.

2024-09-12 08:00 UTC, kerimisoffline commented on app/src/main/java/com/example/backgroundapp/view/IntroFragment.kt
> +        binding.buttonStart.setOnClickListener {
burada crash'e sebep olabilir çünkü view henüz oluşmamış, onviewcreated içerisine alalım.

2024-09-12 08:00 UTC, kerimisoffline commented on app/src/main/java/com/example/backgroundapp/view/ProfileFragment.kt
> +        val layoutManager = GridLayoutManager(context, 2)
buradan aşağısını da onViewcreated içerisinde tanımlayalım.

2024-09-12 08:00 UTC, kerimisoffline commented on app/src/main/java/com/example/backgroundapp/viewmodel/DetailViewModel.kt
> +        val photoRef = firestore.collection("users").document(userId).collection("saved_photos")
"user" ve "saved_photos" constant olarak tanımlayalım.

2024-09-12 08:00 UTC, kerimisoffline commented on app/src/main/java/com/example/backgroundapp/viewmodel/SignupViewModel.kt
> +            errorMessage.value = "Please fill in all fields."
```
 private val errorMessage = MutableLiveData<Int>()
    val errorMessageLiveData: LiveData<Int> get() = errorMessage
```

string.xml den alsın. 
errorMessage int değer dönsün ve tanımlamayı R.id.fill_empty tarzında yapabiliriz.

onu dinlediğimiz fragmentta getString() şeklinde kullanabiliriz.

2024-09-12 13:05 UTC, TamerSarioglu requested changes

2024-09-12 13:05 UTC, TamerSarioglu commented on app/src/main/java/com/example/backgroundapp/model/Photo.kt
> +    data class Links(
Resolved olarak görülüyor issue ancak hala iç içe data kullanımı mevcut.

2024-09-12 13:05 UTC, TamerSarioglu commented on app/src/main/java/com/example/backgroundapp/util/Constants.kt
> +    const val BASE_URL = "https://api.unsplash.com/"
Uygulama api keylerini artık içerde tutmuyoruz. Bunun için özel yöntemler mevcut. Buildconfig içerisinde tutmak gibi. Araştırabilirsin.

2024-09-12 13:05 UTC, TamerSarioglu commented on app/src/main/java/com/example/backgroundapp/view/BottomNavActivity.kt
> +        binding.navView.visibility = View.GONE
Extention olabilir bu fonksiyonlar.

2024-09-12 13:05 UTC, TamerSarioglu commented on app/src/main/java/com/example/backgroundapp/view/CategoryFragment.kt
> +            Category(
Category Data classının olduğu yerde taşıyabilirsin bu listeyi.

2024-09-12 13:05 UTC, TamerSarioglu commented on app/src/main/java/com/example/backgroundapp/view/DetailFragment.kt
> +                    Log.d("DetailFragment", "Image loaded: ${image.urls?.full}")
Loglar kaldırılabilir.

2024-09-12 21:13 UTC, kerimisoffline approved these changes

2024-09-15 15:02 UTC, merged